name: Demo to Create Automatic Pull Request

on:
    push:
        branches:
        - testing


jobs:
    Testing-GitHub-Actions-Job-1:
        runs-on: ubuntu-latest
        steps:
        - name: Repo in Testing Branch is Updated
          run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        
        - name: Checkout The Testing Branch
          run: git checkout origin/testing
          
        - name: Create Pull Request
          run: gh pr create --title "New PR Has Been Created" --body "Could you please review the new changes?" --reviewer johnzan0743 --base main --head testing
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
